### ISSUE TITLE
ValueError: Path cannot be empty

### ISSUE THREAD

**Issue by alexmanase** [spatie/laravel-mail-preview#99]
Hi there!

### Description

I tried to preview some mails on my local environment, and I've got this error when I tried to see previews on the package's route.

https://flareapp.io/share/x7Xk26OP#F37

I looked on Google and I found the same issue when using Laragon. It was something with tmp directory. Unfortunately, I don't use Laragon and those solutions were not solving my problem. I use Valet.

https://laracasts.com/discuss/channels/laravel/error-valueerror-path-cannot-be-empty-in-file

### Information

Laravel Version: 9.24.0  
PHP Version: 8.1.10  
Composer Version: 2.4.1

Thank you!

**Comment by bernhardh** [comment]
How did you solve this issue? I have the same

**Comment by JSFTI** [comment]
In case somebody also have this problem, the error is thrown by `file_get_contents`. The error occurs because `$storedMailPath` is `null`. The variable is null due to the request not having the `file_type` attribute. What I found weird is that the validation did not throw an error. Maybe because the required rule is not used?

Anyway, one way to fix this is adding `?file_type=html` to the preview URL. Based on [this line](https://github.com/spatie/laravel-mail-preview/blob/59b14f3d5c76848f86a83ab077f83fb4ca9b37f1/src/Http/Controllers/ShowMailController.php#L20C1-L20C45), the package will display the latest preview.
